### ISSUE TITLE
if you press decloak and fire at the same time it will give priority to the fire action and make you stab

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#134]
There is literally no reason why someone would press both at once and want to stab; doing so negates the point of decloak-clicking.

**Comment by harmjanhaisma** [comment]
i hope this fixes the issue: when both the uncloak and fire are being held, the spy fires his revolver (uncloaked), i got this working, shall i contribute?

**Comment by wareya** [comment]
Thanks.

**Comment by Medo42** [comment]
It shouldn't be hard to complete harmjanhaisma's fix using the comments in the second pull request. Unfortunately they didn't finish it themselves, probably because having your code criticized feels like having obstacles thrown in your way... It's hard to find a good solution for that.

I'm using my phone, so it's hard to edit tags, but maybe we should mark this as "up for grabs" and "easy" now that the solution has basically been outlined already.
