### ISSUE TITLE
Random return of the arena div0 error

### ISSUE THREAD

**Issue by ZaSpai** [Gang-Garrison-2/Gang-Garrison-2#143]
After having thought this error was resolved a while back, I woke up to find that this error had occurred on my server during a 4v4 arena match (did not take a screenshot of the map or recall the map name, sorry).

Build was GG2 2.7.4.

Error code as below (which I suspect is the same as last time):

___________________________________________
ERROR in
action number 1
of  Step Event
for object ControlPoint:

Error in code at line 198:
           capTime = baseCapTime * livereds/reds;
                                            ^
at position 43: Division by 0.

No server-sent plugins (just chat_v2) or host-sent plugins that I am using affect the ControlPoint object.

**Comment by arctic5** [comment]
https://github.com/Medo42/Gang-Garrison-2/pull/254
https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Objects/Map%20elements/Gamemode-specific/CP/ControlPoint.events/Step.xml

**Comment by Medo42** [comment]
The PR mentioned changed nothing in terms of behaviour, the bug was actually already fixed before that. The fix just isn't in 2.7.4.

**Comment by arctic5** [comment]
wait wtf its not? i thought it was but for some reason it was broken so i replaced it with derps fix

**Comment by Medo42** [comment]
If something doesn't behave like you expect,  you should check your
assumptions and investigate until you understand the problem. Only then
should you try to fix it. If you don't understand the problem correctly,
your fixes might still work sometimes, but they could also do nothing at
all, make things even worse, or hide a deeper issue that will continue to
cause other symptoms. Unfortunately you like to jump straight to fixing. If
you think "isn't this already fixed" next time, look up the source of the
version the bug was reported against.

jason <notifications@github.com> schrieb am So., 15.03.2015, 3:06:

**Comment by arctic5** [comment]
well, i did check but i guess i cracked open the wrong gmk file
