### ISSUE TITLE
Iunno much about GM, but I got this while afk hosting

### ISSUE THREAD

**Issue by JerseyJackal** [Gang-Garrison-2/Gang-Garrison-2#148]
Server Info:

Classlimits = 1 (all)
Player Limits = 13
Operating System = Windows 8.1 Pro (I turned off GM's sound with f12)
RAM = 16GB @ 1600MHz

Comment: Again, I know nothing of GM development, and it occurred while asleep so I have no clue what caused this otherwise. I'll try and do some poking around with it later or something and try to reproduce it.

ERROR in
action number 1
of Begin Step Event
for object GameServer:

In script GameServerBeginStep:
In script processClientCommands:
In script checkClasslimits:
Error in code at line 9:
   if (countClassmembersExcept(player, newTeam, desiredClass) < global.classlimits[desiredClass])
                                                                       ^
at position 70: Unknown variable classlimits or array index out of bounds

**Comment by wareya** [comment]
Looks like a bug. Thanks!

**Comment by wareya** [comment]
Do also let us know if you have any issues when you turn sound on. We did our best to fix those by changing some code when running on Win8, but we're not positive it works for all cases of crashing.

**Comment by arctic5** [comment]
u kno i think this might have been something i unintentionally broke lemme look into it

**Comment by arctic5** [comment]
actually nvm i dont think thats it

**Comment by Medo42** [comment]
While I don't know how this came about exactly, the most likely scenario seems to be that the server actually received a request to switch someone to a nonexistent class. The error would happen regardless of whether classlimits were actually in effect.

There is code in place that's supposed to stop this kind of issue (nothing that is sent from a client should make the server error out), but it's all kinds of broken because `getCharacterObject` has completely useless error checking that furthermore would do the wrong thing even if it worked.

**Comment by Medo42** [comment]
1. `ds_map_find_value` returns 0 if the key does not exist, not -1
2. show_error in a function that's used on the server for input validation is an absolute no-no

**Comment by Medo42** [comment]
At least the server crashing part should be fixed by https://github.com/Medo42/Gang-Garrison-2/commit/d820a11192f872aa30cdac2e1a51fcd6f5ad9725
