### ISSUE TITLE
Error message due to player having an invalid team when trying to spawn in a CP map

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#149]
___________________________________________
ERROR in
action number 1
of Alarm Event for alarm 5
for object Player:

In script selectSpawnGroup:
Error in code at line 52:
       if (group != -1) while (group > 0)
           ^
at position 10: Unknown variable group

**Comment by Medo42** [comment]
This must have been on a map with a `ControlPointHUD`.
The following possibilities exist:
- ControlPointHUD.mode was neither 0 nor 1
- ControlPointHUD.mode was 0, and team was neither TEAM_RED nor TEAM_BLUE

Further investigation required :)

**Comment by Medo42** [comment]
I didn't say that. I just need to look at something else right now and wanted to record what I figured out so far.

**Comment by Medo42** [comment]
Pretty sure that ControlPointHUD.mode is always 0 or 1, so it must have been 0 and the team was invalid.

**Comment by Medo42** [comment]
Further investigation suggests that this might be related to #148 and probably has the same root cause - either a bug that leads to the protocol getting out of sync / the client sending silly requests, or someone is intentionally messing around and sending these.

In any case, the fix committed related to #148 also applies here and probably keeps servers from feeling any ill effects (they'll just ignore the requests), though as mentioned that doesn't explain why the requests are even sent, so there might be another bug lurking.

**Comment by arctic5** [comment]
should be fixed here https://github.com/Medo42/Gang-Garrison-2/commit/d820a11192f872aa30cdac2e1a51fcd6f5ad9725
