### ISSUE TITLE
Glitchy sounding/looking Medigun

### ISSUE THREAD

**Issue by LeNamedMerc** [Gang-Garrison-2/Gang-Garrison-2#177]
Sometimes the Medigun sound loops rapidly and it's color rapidly switches whenever I activate it.

**Comment by Kostia4381** [comment]
Happens to me too, but I find that only when hosting with plugins. Basically, when the weapon re-appears on screen, it glitches out for a while.

**Comment by Medo42** [comment]
Which plugins are you using?

**Comment by Kostia4381** [comment]
Of the plugins that I suspect, carriers and overheal. Carriers uses the visible tag so if you start healing the person, and hide your medigun you'll still heal them, but when the medigun reappears it starts rapidly changing sprites. I don't know how overheal works though.

**Comment by Medo42** [comment]
As for the visual glitch, the medigun draw code "thinks" that it is in recoil or reloading mode (probably reloading).

In the Carriers plugin, it seems to happen because the code that hides the weapon sets alarm[5] of the weapon which activates the "reload" logic in the draw code, but the sprite is never changed to the reloading sprite. Normally this happens after the recoil finishes, in the Alarm 6 Event code, but since this reloading isn't caused by shooting there is no recoil, and the alarm 6 is never started.

However, after reading the code I figured out how you can trigger the same effect in vanilla GG2, and it's actually very easy to reproduce: Just shoot with your needlegun, then immediately heal someone for a very short time. For the remaining duration of the reload, you get the changing colors.

**Comment by Medo42** [comment]
This should fix the glitchy colors part at least, in both cases. It should also be compatible with existing plugins unless they specifically mess with the reload or recoil animations. There is a wider issue in there hinted at by the sound glitching, which is probably related to desync. However, without further information this would be excessively hard to track down, so I'm closing this until someone provides more info.
