### ISSUE TITLE
Unknown variable _last_hspeed

### ISSUE THREAD

**Issue by Medo42** [Gang-Garrison-2/Gang-Garrison-2#187]
Reported by Heapons:
"Everytimes i or someone taunt =("
___________________________________________
ERROR in
action number 1
of Begin Step Event
for object Character:

Error in code at line 188:
               if(sign(_last_hspeed) > 0)
                      ^
at position 21: Unknown variable _last_hspeed

**Comment by Derpduck** [comment]
Looks like it's from a plugin lol.

**Comment by ZaSpai** [comment]
What Derp said since _last_hspeed isn't defined in base code
Doesn't appear to be GG2Stats based or WoodNeck GG2i based, but I'm guessing it relates to something that modifies the taunt sprites

**Comment by Medo42** [comment]
"everyserver (include these i hosted by myself) and when someone/me is taunting (and sometimes for unknow reasons) it makes me permanent errors and this without plugins but it seems to work fine when i'm modding the game (idk how is possible)."

So, he claims this is without plugins.

**Comment by ZaSpai** [comment]
The last error Heapons had and claimed was not plugin mediated actually ended being due to plugins so I wouldn't put complete faith in that
I would suggest he re-installs GG2 into a new directory and tries again, if the fresh exe doesn't throw errors there must be something with either the exe he's running normally or a host based plugin that is causing these errors

**Comment by wareya** [comment]
Closing, probably not a vanilla bug.
