### ISSUE TITLE
Lobby claims to show 4/4 servers, but list only shows two

### ISSUE THREAD

**Issue by NameOfClash** [Gang-Garrison-2/Gang-Garrison-2#191]
I joined Gang Garrison 2 and clicked join lobby,server has 4 lobbies but i can't see 2 lobbies. Please help me https://prnt.sc/fqa5wx

**Comment by Medo42** [comment]
Looking through the code, this could happen if the ping to these servers takes a long time without failing entirely, because the servers are only added to the list once the ping is done.

We should probably add a timeout to ensure they are added eventually (a cutoff at 1 or 2 seconds is probably plenty).
