### ISSUE TITLE
Joining a server while in the server? What?

### ISSUE THREAD

**Issue by Kostia4381** [Gang-Garrison-2/Gang-Garrison-2#194]
I was just playing vanilla GG2 when THIS happened.

![game pls](https://user-images.githubusercontent.com/21104932/30241363-b2fcbf14-958a-11e7-9437-30661d66a62b.png)

It seems like the game is trying to connect to a server while a GameServer exists..

**Comment by wareya** [comment]
The "cthulhu" tag I just added isn't really a joke - this is a very obscure bug that's very rare and been around for a long time, and we have no idea what it is.

**Comment by Medo42** [comment]
Yeah, I don't really want to close this but we also cannot directly work on it. I think the task here is "add better debugging capability for protocol desync".

**Comment by Medo42** [comment]
I just spent way too much time trying to figure out whether it's possible to work back from where it got stuck and the characters that it's showing. I *think* the character set is CP437+CP872. However, after looking at the protocol that knowledge is completely useless, because the client will have received several length-prefixed strings before the plugins list, so there was an unknown amount of unknown data since the protocol "disagreement" happened.

**Comment by Medo42** [comment]
Continued in #203
