### ISSUE TITLE
Background change on "Host Game"

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#217]
Only happens sometimes
1) Open GG2 without MainMenu-related plugins
2) Wait for background change
3) Click on "Host Game" and then on "Back" until the background is stuck as the options menu one. Doing step 3 again will reset the background to the downloaded one
Downloaded Menu => Wrong menu
![Imgur](https://i.imgur.com/TVYjaMT.png) ![Imgur](https://i.imgur.com/4FgnA6o.png)
Edit: it doesn't show here, but using RBackgrounds it seems the title and link are still shown

**Comment by PrOF-kk** [comment]
Found the issue: MainMenuController chooses between MainMenu1 and MainMenu2 every time it's created, leading to it changing when changing screen. Since the default background is always used for Options I'll post a pr making it default to the first background. Why was the background set to default in devmessages.txt?

**Comment by Medo42** [comment]
Hmm, I rather like that it chooses a random background when starting the game (else what is the other one for?). Maybe we should put the choice into game_init so it can be consistent in the menus instead of removing it.

Also, the devmessages.txt background is default now because we had the competition background for quite a while and while it's nice I though we should have the original backgrounds again for a bit.
