### ISSUE TITLE
Rocketjumping Soldiers fail to rocketjump while ubered

### ISSUE THREAD

**Issue by BasedUser** [Gang-Garrison-2/Gang-Garrison-2#233]
When a Soldier has ubercharge, his own rockets don't set the movestatus to 1 because the ubered condition doesn't check if the rocket is his own. It's mainly a code issue, adding a condition to see if the rocket is his own would probably fix this.

```//in rocket user 5
        with (Character) {
            if (distance_to_object(other) < other.blastRadius and !(team == other.team and id != other.ownerPlayer.object and place_meeting(x, y+1, Obstacle))){
                //...
                if(!ubered and hp > 0)
                {
                    //...
                } else {
                    if hp > 0 and id==other.ownerPlayer.object and other.team == team and ubered{ //just in case
                        moveStatus = 1;
                        speed*=1.06;
                    }
                }
            }
        }
```
I know that I could have done a pull request, but I'm way too lazy to create my own branch; plus this acts as a pointer for a potential bugfix.

**Comment by Medo42** [comment]
Thank you, I'll pull it in for the next version (if history is any guide, that's probably around the end of the year :))

**Comment by Kostia4381** [comment]
The bug existed since 2.4, I have no idea how none of the devs found it, and how noone reported this

**Comment by wareya** [comment]
Gang Garrison 2 has a lot of weird behaviors that aren't obvious whether
they're intentional or not, so players and devs alike get used to how
different stuff works in different situations. For example, velocity had a
circle-shaped limit, but this made you fall slower if you were holding left
or right, so it changed to a square shape, but that made sticky jumping too
powerful, and we do something weird now, I think. It's not always obvious
whether something should get fixed or not. I say that as the person who
hooked up movestatus to rocketjumping originally.

**Comment by Medo42** [comment]
Alright, I also added equivalent code for the mine explosions.
