### ISSUE TITLE
Servers started on 01/04 lock bubbles even on other days

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#241]
We only check if it's April 1st on startup, so servers get stuck only allowing the scout emote (which on april first is set to Bassieface)
[Link to game_init, where the check happens](https://github.com/Medo42/Gang-Garrison-2/blob/ed82dd0c0d923a1dd62e0308abc8f4be09ba35e2/Source/gg2/Scripts/Game/game_init.gml#L373)
As seen [here](https://www.ganggarrison.com/forums/index.php?topic=38317.msg1296517#msg1296517)

**Comment by PrOF-kk** [comment]
Why do we [lock the bubble number being sent](https://github.com/Medo42/Gang-Garrison-2/blob/ed82dd0c0d923a1dd62e0308abc8f4be09ba35e2/Source/gg2/Scripts/GameServer/processClientCommands.gml#L196-L199) even if we [assign every bubble to bassieface](https://github.com/Gang-Garrison-2/Gang-Garrison-2/blob/master/Source/gg2/Scripts/Holidays/calculateMonthAndDay.gml#L20-L21) client-side?

**Comment by wareya** [comment]
server and client can disagree about what time it is

**Comment by wareya** [comment]
(so I can't tell if this is a bug, in fact it might be one)

**Comment by wareya** [comment]
global.aFirst should be refreshed on map change

**Comment by PrOF-kk** [comment]
I thought about doing that, but we could also let the client handle this on its own, so it's still only checked on startup

**Comment by wareya** [comment]
it should be if the server Or client think it's april fool's day

**Comment by PrOF-kk** [comment]
Looks to me like all the other holidays are handled only client-side, why bother with April 1st?

**Comment by wareya** [comment]
it's gg2's traditional release date, and also, a lack of real bubble communication technically affects gameplay

**Comment by Medo42** [comment]
If we want to care about that we should let the server check this on every mapchange as wareya suggests, and sync the information to the clients.

**Comment by PrOF-kk** [comment]
Hmm, I'd like to keep things simple, how about we check server-side on map change and remove the lock, without changing anything client-side? It's not flawless against edge cases, but it's simple

**Comment by Medo42** [comment]
The code should be consistent with some narrative of design goals. If we acknowledge that the bubbles are relevant to gameplay then the consequence has to be that everyone in a match has the same constraints in that regard, and that doesn't work if you make the April 1st decision client-side.

**Comment by PrOF-kk** [comment]
If we make both server and client check on map change we should be fine, in any case the server has priority

**Comment by Medo42** [comment]
I solved this now by making the Bassieface a normal bubble index that the server can send when it thinks that's a good idea. Also the server will re-check whether it's April 1st every 30 seconds.

However, this also had the initially-unintended-but-I-kind-of-like-it-now effect that some gameplay-relevant bubbles are not replaced:
- Medic! was actually excluded in the serverside bubble locking code, probably to keep the medic radar working. Since we no longer do sprite replacement, Medic! bubble is now shown normally on April 1st.
- "I'm burning!" and "Sentry down!" are generated client-side and now show the actual bubble, too.

If you think that *all* bubbles should be Bassieface then please re-open.
