### ISSUE TITLE
Jump Dust particles last half as much in 60fps

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#264]
```
part_type_life(ind, life_min, life_max);  
You provide a minimum and a maximum value (in steps) and each particle lifespan  
will be a random number of steps from within the specified range.
```
We probably need to deltatime this:
https://github.com/Gang-Garrison-2/Gang-Garrison-2/blob/195b4521a7264bfc156cc97912a235c6627ff11c/Source/gg2/Objects/InGameElements/Character.events/Begin%20Step.xml#L233
60fps also affects `part_type_speed`, but we don't use it here

**Comment by Medo42** [comment]
Nice catch, also affects two more places (alternative particles for flames and flares, as well as rocketjumping particles). With the Flames and Flares I had to change the creation code for the particle type a bit, since it's a global variable where the others are local ones that get recreated for each object.
